// sqrt_lut.v
// Computes sqrt(1 - s3^2) via lookup table for the arcsin-to-arctan conversion:
// arcsin(S3) = arctan(S3 / sqrt(1 - S3^2)).

module sqrt_lut #(
    parameter W        = 18,             // output word width, Q1.(W-2) format
    parameter LUT_FILE = "sqrt_lut.hex"  // precomputed by scripts/gen_sqrt_lut.py
)(
    input  wire                clk,
    input  wire                rst_n,    // active-low asynchronous reset

    input  wire signed [W-1:0] s3_in,   // S3 Stokes parameter, Q1.(W-2), range [-1, 1]
    input  wire                in_valid,

    // sqrt(1 - s3_in^2), Q1.(W-2) format, range [0, 1]. Latency: 1 clock cycle.
    output reg  signed [W-1:0] sqrt_out,
    output reg                 out_valid
);

    // 2048-entry ROM: lut[k] = round(sqrt(1 - (k/2048)^2) * 2^(W-2))
    // indexed by |S3| — symmetric around 0 so only the positive half is stored.
    // generated by scripts/gen_sqrt_lut.py.
    reg [W-1:0] lut [0:2047];
    initial $readmemh(LUT_FILE, lut);

    // absolute value of s3_in (two's complement negation)
    wire [W-1:0] s3_abs = s3_in[W-1] ? (~s3_in + 1'b1) : s3_in;

    // convert Q1.(W-2) absolute value to 11-bit LUT index in [0, 2047].
    // s3_abs represents values in [0, 1]; dividing by 2^(W-13) maps to [0, 2048].
    // clamp to 2047 for the edge case s3 = -1.0 exactly (s3_abs = 2^(W-2) = 65536).
    localparam IDX_SHIFT = W - 13;                                     // for W=18: shift by 5
    wire [11:0] lut_idx_raw = s3_abs[W-2:IDX_SHIFT];                  // 12 bits, range [0, 2048]
    wire [10:0] lut_idx     = (lut_idx_raw > 12'd2047) ? 11'd2047 : lut_idx_raw[10:0];

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            sqrt_out  <= 0;
            out_valid <= 1'b0;
        end else begin
            out_valid <= in_valid;
            sqrt_out  <= lut[lut_idx];
        end
    end

endmodule
